/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exam.gui;

import exam.all.DBMgr;
import exam.all.Exam;
import static exam.gui.ScheduleExamGUI.errorBox;
import static exam.gui.ScheduleExamGUI.infoBox;
import java.awt.Color;

/**
 *
 * @author jordancutler, Lizzie Litt
 */
public class IntermediateViewExamGUI extends javax.swing.JFrame {

    /**
     * Creates new form IntermediateViewExamGUI
     */
    public IntermediateViewExamGUI() {
        initComponents();
        this.getContentPane().setBackground(Color.pink);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        directionLabel = new javax.swing.JLabel();
        examNumberField = new javax.swing.JFormattedTextField();
        viewExamButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        directionLabel.setText("Enter the exam number to view:");

        examNumberField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        viewExamButton.setText("View Exam");
        viewExamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewExamButtonActionPerformed(evt);
            }
        });

        backButton.setText("Return to Main Menu");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exam/gui/logo small.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(examNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(directionLabel))
                .addGap(119, 119, 119))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel1))
                            .addComponent(backButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(viewExamButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(directionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(examNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewExamButton)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewExamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewExamButtonActionPerformed
        // TODO add your handling code here:
        if (examNumberField.getValue() == null) {
            errorBox("Please enter an exam number.");
            return;
        }
        int procedureNumber = 0;
        /*if (procedureNumberField.getValue() > Integer.MAX_VALUE || procedureNumberField.getValue() <= (long)0) {
            errorBox("Please enter a valid procedure number.");
        }
        else {
            */
        try {
            procedureNumber = (Integer.parseInt(examNumberField.getText()));
        } catch (Exception e) {
            System.out.println(e.getMessage());
            errorBox("Please enter a valid procedure number.");
            return;
        }
        /*if (procedureNumber <= 0) {
            errorBox("Please enter a valid procedure number.");
            return;
        }*/
        DBMgr instance = DBMgr.getInstance();
        Exam retrievedExam = null;
        try {
            retrievedExam = instance.viewExam(procedureNumber);
        } catch (Exception e) {
            System.out.println(e.getMessage());
            errorBox("An error occurred trying to retrieve the exam from the database.");
            return;
        }
        if (retrievedExam == null) {
            infoBox("This procedure number was not found. Please try again.");
            return;
        }
        if (retrievedExam != null) {
            new ViewExamGUI(retrievedExam.getBuilding(), retrievedExam.getExamType(), 
                    retrievedExam.getDoctor(), retrievedExam.getPatient(),
                    retrievedExam.getRoomNumber(), retrievedExam.getStatus(), 
                    retrievedExam.getActualStartTime(), retrievedExam.getActualEndTime(), 
                    retrievedExam.getPlannedTime(), 
                    retrievedExam.getEndTime(), retrievedExam.getExamNumber()).setVisible(true);
            
            this.dispose();
        }
    }//GEN-LAST:event_viewExamButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.dispose();
        MainGUI.makeGUIVisible();
    }//GEN-LAST:event_formWindowClosing

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        MainGUI.makeGUIVisible();
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntermediateViewExamGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntermediateViewExamGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntermediateViewExamGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntermediateViewExamGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntermediateViewExamGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel directionLabel;
    private javax.swing.JFormattedTextField examNumberField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton viewExamButton;
    // End of variables declaration//GEN-END:variables
}
