/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exam.gui;

import exam.all.DBMgr;
import static exam.gui.ScheduleExamGUI.errorBox;
import static exam.gui.ScheduleExamGUI.infoBox;
import java.awt.Color;

/**
 *
 * @author jordancutler, Lizie Litt
 */
public class StartOrEndExamGUI extends javax.swing.JFrame {
    boolean start;
    static int startOrEndVar;
    /**
     * Creates new form UpdateExamGUI
     */
    public StartOrEndExamGUI(int startOrEnd) {
        initComponents();
        this.getContentPane().setBackground(Color.pink);
        if (startOrEnd == 1) {
            start = true;
        }
        else {
            start = false;
        }
        startOrEndVar = startOrEnd;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        directionLabel1 = new javax.swing.JLabel();
        examNumberField = new javax.swing.JFormattedTextField();
        doneButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        directionLabel1.setText("Enter the exam number:");

        examNumberField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        examNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examNumberFieldActionPerformed(evt);
            }
        });

        doneButton.setText("Done");
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });

        backButton.setText("Return to Main Menu");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exam/gui/logo small.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(directionLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(examNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(doneButton)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backButton)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(directionLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(examNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(doneButton)
                .addGap(96, 96, 96))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        // TODO add your handling code here:
        if (examNumberField.getValue() == null) {
            errorBox("Please enter an exam number to start the exam.");
            return;
        }
        int procedureNumber = 0;
        /*if (procedureNumberField.getValue() > Integer.MAX_VALUE || procedureNumberField.getValue() <= (long)0) {
            errorBox("Please enter a valid procedure number.");
        }
        else {
            */
        try {
            procedureNumber = (Integer.parseInt(examNumberField.getText()));
        } catch (Exception e) {
            System.out.println(e.getMessage());
            errorBox("Please enter a valid procedure number.");
            return;
        }
        if (procedureNumber <= 0) {
            errorBox("Please enter a valid procedure number.");
            return;
        }
        
        /* search for the exam based on the procedure number entered.
        If the procedure number was not found, give an error and say it wasnt found.
        If it was found, set the actual time to a new Date().
        */
        if (start) {
            DBMgr instance = DBMgr.getInstance();
            Boolean started = false;
            try {
                started = instance.startExam(procedureNumber);
                    } catch (Exception e) {
                        System.out.println ("Start Exam: An invalid exam number was entered");
                        System.out.println(e.toString());
                        return;
                    }
            if (started)
                infoBox("Exam will be started");
            else
                infoBox("Exam has already been started");
        }
        else {
            DBMgr instance = DBMgr.getInstance();
            Boolean ending = false;
            try {
                System.out.println("Called end exam");
                ending = instance.endExam(procedureNumber);
                    } catch (Exception e) {
                        System.out.println ("End Exam: An invalid exam number was entered");
                        System.out.println(e.toString());
                        return;
                    }
            if (ending)
                infoBox("Exam will be ended");
            else
                infoBox("Exam has not been started or is already finished");
        }
        this.dispose();
        MainGUI.makeGUIVisible();
    }//GEN-LAST:event_doneButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        MainGUI.makeGUIVisible();
    }//GEN-LAST:event_backButtonActionPerformed

    private void examNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examNumberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_examNumberFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartOrEndExamGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartOrEndExamGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartOrEndExamGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartOrEndExamGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartOrEndExamGUI(startOrEndVar).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel directionLabel1;
    private javax.swing.JButton doneButton;
    private javax.swing.JFormattedTextField examNumberField;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
